import { Inter } from "next/font/google";
import "./globals.css";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Providers } from "@/providers/Providers";

import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);


  return (
    <html lang="en">
      <body >
        <Providers session={session}>
          {children}
        </Providers>

      </body>
    </html>
  );
}
